version: '3.7'

services:
  web:
    build: ""
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cargos_backend/:/usr/src/cargos_backend/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cargos_admin
      - POSTGRES_PASSWORD=cargos_admin
      - POSTGRES_DB=cargos_storage

volumes:
  postgres_data: